services:
  # Cardigann
  cardigann:
    image: linuxserver/cardigann:latest
    container_name: cardigann
    volumes:
      - ${BASE_DIR}/cardigann/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: always
