dist: xenial
sudo: required
language: minimal
before_install:
  - cd .tests/ && curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - sudo pip install -U bashate
  - cd ..
addons:
  apt:
    update: true
jobs:
  include:
    - stage: validate
      script: 
        - sudo bash ./media-docker.sh -t v_bashate
        - sudo bash ./media-docker.sh -t v_shellcheck
    - stage: test
      script: 
        - sudo bash ./media-docker.sh -t t_unit
branches:
  only:
    - master
