matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
language: minimal
jobs:
  include:
    - stage: validate
      script: sudo bash ./media-docker.sh -t v_bashate
      script: sudo bash ./media-docker.sh -t v_shellcheck
    - stage: test
      script: sudo bash ./media-docker.sh -t t_unit
