dist: xenial
sudo: required
language: minimal
before_install:
  - sudo apt-get install -y xz-utils shunit2
  - sudo pip install -U bashate
addons:
  apt:
    update: true
jobs:
  include:
    - stage: validate
      script: 
        - sudo bash ./media-docker.sh -t v_bashate
        - sudo bash ./media-docker.sh -t v_shellcheck
    - stage: test
      script: sudo bash ./media-docker.sh -t t_unit
