services:
  # Traefik
  traefik:
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DIR}/traefik/traefik.toml:/traefik.toml
      - ${BASE_DIR}/traefik/acme.json:/acme.json
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=8080
    networks:
      - proxied
      - internal
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    restart: always
