services:
  # Ombi
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    volumes:
      - ${BASE_DIR}/ombi/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    depends_on:
      - plex
    restart: always
