services:
  # Beets
  beets:
    image: linuxserver/beets:latest
    container_name: beets
    volumes:
      - ${BASE_DIR}/beets/config:/config
      - ${MEDIA_DIR}/Music:/movies
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
