services:
  # Oscarr
  oscarr:
    image: morpheus65535/oscarr:latest
    container_name: oscarr
    volumes:
      - ${BASE_DIR}/morpheus65535/config:/oscarr/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
