services:
  # Couchpotato
  couchpotato:
    image: linuxserver/couchpotato:latest
    container_name: couchpotato
    volumes:
      - ${BASE_DIR}/couchpotato/config:/config
      - ${MEDIA_DIR}/Movies:/movies
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
