# Traefik configuration file
# Replace #DOMAIN# with the base domain you would like Traefik to use
# for reverse proxying.
#
# Replace #EMAIL_ADDRESS# with the email address you would like to receive
# Let's Encrypt notifications at.

defaultEntryPoints = ["http","https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.traefik.auth.basic]
    usersfile = "/traefik.passwd"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
endpoint="unix:///var/run/docker.sock"
domain="#DOMAIN#"
watch=true

[acme]
email = "#EMAIL_ADDRESS#"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[acme.httpChallenge]
  entryPoint = "https"
