services:
  # Ubooquity
  ubooquity:
    image: linuxserver/ubooquity:latest
    container_name: ubooquity
    volumes:
      - ${BASE_DIR}/ubooquity/config:/config
      - ${MEDIA_DIR}/Books:/books
      - ${MEDIA_DIR}/Comics:/comics
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: always
